/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TESTE_H_RPCGEN
#define _TESTE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operands {
	int x;
	int y;
};
typedef struct operands operands;

#define SIMP_PROG 0x2fffffff
#define SIMP_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define SOM 1
extern  int * som_1(operands *, CLIENT *);
extern  int * som_1_svc(operands *, struct svc_req *);
#define MUT 2
extern  int * mut_1(operands *, CLIENT *);
extern  int * mut_1_svc(operands *, struct svc_req *);
#define DIVI 3
extern  int * divi_1(operands *, CLIENT *);
extern  int * divi_1_svc(operands *, struct svc_req *);
#define SUB 4
extern  int * sub_1(operands *, CLIENT *);
extern  int * sub_1_svc(operands *, struct svc_req *);
#define MOD 5
extern  int * mod_1(operands *, CLIENT *);
extern  int * mod_1_svc(operands *, struct svc_req *);
#define POT 6
extern  int * pot_1(operands *, CLIENT *);
extern  int * pot_1_svc(operands *, struct svc_req *);
#define RAIZ 7
extern  int * raiz_1(operands *, CLIENT *);
extern  int * raiz_1_svc(operands *, struct svc_req *);
extern int simp_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SOM 1
extern  int * som_1();
extern  int * som_1_svc();
#define MUT 2
extern  int * mut_1();
extern  int * mut_1_svc();
#define DIVI 3
extern  int * divi_1();
extern  int * divi_1_svc();
#define SUB 4
extern  int * sub_1();
extern  int * sub_1_svc();
#define MOD 5
extern  int * mod_1();
extern  int * mod_1_svc();
#define POT 6
extern  int * pot_1();
extern  int * pot_1_svc();
#define RAIZ 7
extern  int * raiz_1();
extern  int * raiz_1_svc();
extern int simp_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operands (XDR *, operands*);

#else /* K&R C */
extern bool_t xdr_operands ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TESTE_H_RPCGEN */
